In [9]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [10]:
loss

tensor(0.8060, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

一位数autograd的使用

In [11]:
x = torch.randn(1)
y = torch.zeros(1)
w = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
z = torch.matmul(x, w) + b
z.backward()

In [13]:
x

tensor([0.3391])

In [12]:
z.grad_fn

loss 对w和b的梯度

In [15]:
w.grad,b.grad

(tensor([[0.3391]]), tensor([1.]))

In [17]:
x.requires_grad

False

In [19]:
a = torch.randn((3,3))
a.requires_grad = True

In [20]:
c = 2 * a
c.requires_grad

True

In [21]:
with torch.no_grad():
    d = 2 * a
d.requires_grad

False

In [22]:
c.requires_grad

True

In [24]:
c.detach().requires_grad,c.requires_grad

(False, True)

In [46]:
length = 10 ** 4
a = torch.randn(length)
b = torch.normal(0.,1.,(1,length))
a.shape,b.shape

(torch.Size([10000]), torch.Size([1, 10000]))

In [45]:
torch.sum(a) / length, torch.sum(b) / length

(tensor(1.8724e-05), tensor(4.5258e-05))

In [47]:
torch.var(a),torch.var(b)

(tensor(0.9950), tensor(1.0187))

In [61]:
w = torch.randn(1,requires_grad=True)
w

tensor([-0.9593], requires_grad=True)

In [72]:
a = torch.randn(1)
b = torch.randn(1)
z = a * w + b * w

z.backward()
w.grad, torch.equal(w.grad, a + b)

(tensor([0.7447]), True)

In [75]:
w.grad

tensor([0.7447])

In [88]:
A = a * w
B = b * w

In [80]:
a,b

(tensor([-0.4381]), tensor([1.1828]))

In [85]:
w.grad.zero_()
A.backward()
print(f"w.grad of A: {w.grad}")
B.backward()
print(f"w.grad of B: {w.grad}")

w.grad of A: tensor([-0.4381])
w.grad of B: tensor([0.7447])


In [89]:
w.grad.zero_()
A.backward()
print(f"w.grad of A: {w.grad}")
w.grad.zero_()
B.backward()
print(f"w.grad of B: {w.grad}")

w.grad of A: tensor([-0.4381])
w.grad of B: tensor([1.1828])


In [90]:
inp = torch.eye(4, 5, requires_grad=True)

In [91]:
inp

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)