In [2]:
import torch

定义tensor

In [4]:
tensor = torch.arange(8)
tensor = tensor.view(2, 2, 2)
tensor,tensor.shape

(tensor([[[0, 1],
          [2, 3]],
 
         [[4, 5],
          [6, 7]]]),
 torch.Size([2, 2, 2]))

## cat
在三个维度进行cat

In [9]:
_ = torch.cat([tensor, tensor, tensor], dim=0)
_,_.shape

(tensor([[[0, 1],
          [2, 3]],
 
         [[4, 5],
          [6, 7]],
 
         [[0, 1],
          [2, 3]],
 
         [[4, 5],
          [6, 7]],
 
         [[0, 1],
          [2, 3]],
 
         [[4, 5],
          [6, 7]]]),
 torch.Size([6, 2, 2]))

In [10]:
_ = torch.cat([tensor, tensor, tensor], dim=1)
_,_.shape

(tensor([[[0, 1],
          [2, 3],
          [0, 1],
          [2, 3],
          [0, 1],
          [2, 3]],
 
         [[4, 5],
          [6, 7],
          [4, 5],
          [6, 7],
          [4, 5],
          [6, 7]]]),
 torch.Size([2, 6, 2]))

In [12]:
_ = torch.cat([tensor, tensor, tensor], dim=2)
_,_.shape

(tensor([[[0, 1, 0, 1, 0, 1],
          [2, 3, 2, 3, 2, 3]],
 
         [[4, 5, 4, 5, 4, 5],
          [6, 7, 6, 7, 6, 7]]]),
 torch.Size([2, 2, 6]))

## stack

In [13]:
_ = torch.stack([tensor, tensor, tensor], dim=0)
_,_.shape

(tensor([[[[0, 1],
           [2, 3]],
 
          [[4, 5],
           [6, 7]]],
 
 
         [[[0, 1],
           [2, 3]],
 
          [[4, 5],
           [6, 7]]],
 
 
         [[[0, 1],
           [2, 3]],
 
          [[4, 5],
           [6, 7]]]]),
 torch.Size([3, 2, 2, 2]))

In [14]:
_ = torch.stack([tensor, tensor, tensor], dim=1)
_,_.shape

(tensor([[[[0, 1],
           [2, 3]],
 
          [[0, 1],
           [2, 3]],
 
          [[0, 1],
           [2, 3]]],
 
 
         [[[4, 5],
           [6, 7]],
 
          [[4, 5],
           [6, 7]],
 
          [[4, 5],
           [6, 7]]]]),
 torch.Size([2, 3, 2, 2]))

In [6]:
_ = torch.stack([tensor, tensor, tensor], dim=3)
_,_.shape

(tensor([[[[0, 0, 0],
           [1, 1, 1]],
 
          [[2, 2, 2],
           [3, 3, 3]]],
 
 
         [[[4, 4, 4],
           [5, 5, 5]],
 
          [[6, 6, 6],
           [7, 7, 7]]]]),
 torch.Size([2, 2, 2, 3]))