In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets,transforms

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
device

'cuda'

In [12]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU()
        )
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [13]:
model = NeuralNetwork().to(device)
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)

In [14]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
logits.shape

torch.Size([1, 10])

In [15]:
pred_probab = nn.Softmax(dim=1)(logits)
pred_probab

tensor([[0.0997, 0.1010, 0.0987, 0.0987, 0.0987, 0.0987, 0.0995, 0.0987, 0.1040,
         0.1025]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [17]:
y_pred = pred_probab.argmax(dim=1)
y_pred

tensor([8], device='cuda:0')

In [18]:
input_image = torch.rand(3, 28, 28)
flatten = nn.Flatten()
flat_image = flatten(input_image)
flat_image.shape

torch.Size([3, 784])

In [19]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
hidden1.shape

torch.Size([3, 20])

In [20]:
relu = nn.ReLU()

In [21]:
hidden1

tensor([[ 0.1324, -0.1239,  0.0837,  0.3752,  0.0874,  0.1932, -0.0563,  0.5227,
          0.4143, -0.0009,  0.5537, -0.6164,  0.2399,  0.0187, -0.6695,  0.3361,
         -0.3320,  0.1832, -0.3415, -0.0310],
        [ 0.0597,  0.2896,  0.0268, -0.2163,  0.4434,  0.3501, -0.2420,  0.5989,
          0.4790, -0.3913,  0.0602, -0.1324,  0.2588, -0.0435, -0.8571,  0.1359,
         -0.0895,  0.0435, -0.0318, -0.1440],
        [ 0.0391,  0.2357,  0.0642, -0.1373,  0.0581, -0.1161,  0.1201,  0.7840,
          0.2096,  0.0607, -0.0637, -0.4474,  0.1364,  0.0990, -0.7341,  0.4793,
         -0.2020,  0.1725,  0.0020,  0.0139]], grad_fn=<AddmmBackward0>)

In [22]:
hidden1 = relu(hidden1)
hidden1

tensor([[0.1324, 0.0000, 0.0837, 0.3752, 0.0874, 0.1932, 0.0000, 0.5227, 0.4143,
         0.0000, 0.5537, 0.0000, 0.2399, 0.0187, 0.0000, 0.3361, 0.0000, 0.1832,
         0.0000, 0.0000],
        [0.0597, 0.2896, 0.0268, 0.0000, 0.4434, 0.3501, 0.0000, 0.5989, 0.4790,
         0.0000, 0.0602, 0.0000, 0.2588, 0.0000, 0.0000, 0.1359, 0.0000, 0.0435,
         0.0000, 0.0000],
        [0.0391, 0.2357, 0.0642, 0.0000, 0.0581, 0.0000, 0.1201, 0.7840, 0.2096,
         0.0607, 0.0000, 0.0000, 0.1364, 0.0990, 0.0000, 0.4793, 0.0000, 0.1725,
         0.0020, 0.0139]], grad_fn=<ReluBackward0>)

In [24]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)
print(pred_probab.shape)
pred_probab[0]

torch.Size([1, 10])


tensor([0.0997, 0.1010, 0.0987, 0.0987, 0.0987, 0.0987, 0.0995, 0.0987, 0.1040,
        0.1025], device='cuda:0', grad_fn=<SelectBackward0>)

In [25]:
sum(pred_probab[0])

tensor(1., device='cuda:0', grad_fn=<AddBackward0>)

In [27]:
for name,param in model.named_parameters():
    print(name, "\t\t", param.shape)

linear_relu_stack.0.weight 		 torch.Size([512, 784])
linear_relu_stack.0.bias 		 torch.Size([512])
linear_relu_stack.2.weight 		 torch.Size([512, 512])
linear_relu_stack.2.bias 		 torch.Size([512])
linear_relu_stack.4.weight 		 torch.Size([10, 512])
linear_relu_stack.4.bias 		 torch.Size([10])
