In [6]:
import pandas as pd

In [2]:
nums = [i for i in range(1000)]
labels = [10*i for i in nums]
data = {
    'nums': nums,
    'labels': labels
}
df = pd.DataFrame(data)
df.to_csv('./data/jie/data.csv', index=False)

In [7]:
data_csv = pd.read_csv('./data/jie/data.csv')
data_csv['nums'][0]

0

In [9]:
data_csv.iloc[[1,3,6],1]

1    10
3    30
6    60
Name: labels, dtype: int64

In [1]:
import torch

In [5]:
_ = torch.tensor([1,2,3]).tolist()
type(_)

list

In [2]:
_ = torch.zeros(10)

In [3]:
_

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
_.scatter_(0, torch.tensor([1,3,5]), 1)

tensor([0., 1., 0., 1., 0., 1., 0., 0., 0., 0.])

In [7]:
def ont_hot_encoding(x, num_classes):
    return torch.zeros(num_classes).scatter_(0, x, 1)

ont_hot_encoding(torch.tensor([1,3,5]), 10)

tensor([0., 1., 0., 1., 0., 1., 0., 0., 0., 0.])