## 乘法

In [1]:
import torch

### 矩阵乘法

torch.matmul 与 torch.mm 用法相同，但是 torch.matmul 支持更多的维度，而 torch.mm 只支持二维矩阵的乘法。

In [2]:
a = torch.tensor([[1,2,3],[4,5,6]]) # 2 x 3
b = torch.tensor([[1,2],[3,4],[5,6]]) # 3 x 2

In [3]:
torch.matmul(a,b) # 2 x 2

tensor([[22, 28],
        [49, 64]])

In [7]:
torch.mm(a,b), a @ b

(tensor([[22, 28],
         [49, 64]]),
 tensor([[22, 28],
         [49, 64]]))

### 点乘

In [9]:
c = torch.tensor([[1,2],[3,4]])
d = torch.tensor([[0,1],[2,3]])
c * d

tensor([[ 0,  2],
        [ 6, 12]])

矩阵 * 向量 vs 矩阵 * 矩阵

In [3]:
m1 = torch.tensor([[1,2],[3,4]])
v1 = torch.tensor([1,2])

1. 矩阵 * 向量

向量和矩阵的乘法，可以理解为矩阵的每一行与向量相乘，点乘

In [5]:
m1 * v1

tensor([[1, 4],
        [3, 8]])

2. 矩阵 * 矩阵

特别注意这个

In [6]:
m1 * v1.reshape(2,1)

tensor([[1, 2],
        [6, 8]])

In [7]:
torch.matmul(m1,v1.reshape(2,1))

tensor([[ 5],
        [11]])

In [4]:
torch.matmul(m1,v1)

tensor([ 5, 11])

In [14]:
torch.bmm(m1.unsqueeze(0),v1.reshape(1,2,1)) # must above 3D

tensor([[[ 5],
         [11]]])

## 加法

shape相同按位相加

In [12]:
t1 = torch.arange(1,3).reshape(2,1)
t1,t1.shape

(tensor([[1],
         [2]]),
 torch.Size([2, 1]))

In [16]:
t2 = torch.Tensor([3,4])
t2,t2.shape

(tensor([3., 4.]), torch.Size([2]))

In [17]:
t1 + t2.reshape(2,1)

tensor([[4.],
        [6.]])

广播加法

In [18]:
t1,t2

(tensor([[1],
         [2]]),
 tensor([3., 4.]))

In [19]:
t1 + t2

tensor([[4., 5.],
        [5., 6.]])

In [20]:
t3 = torch.arange(1,5).reshape(2,2)
t3,t3.shape

(tensor([[1, 2],
         [3, 4]]),
 torch.Size([2, 2]))

In [21]:
t2,t3

(tensor([3., 4.]),
 tensor([[1, 2],
         [3, 4]]))

In [22]:
t2 + t3

tensor([[4., 6.],
        [6., 8.]])

In [23]:
t2.reshape(2,1),t3

(tensor([[3.],
         [4.]]),
 tensor([[1, 2],
         [3, 4]]))

In [24]:
t2.reshape(2,1) + t3

tensor([[4., 5.],
        [7., 8.]])