## TensorDataset

1. 需要继承 `Dataset[Tuple[Tensor, ...]]`
2. `__getitem__` 返回的是一个元组，元组中的每个元素都是一个 `Tensor`
3. `__len__` 返回的是数据集的大小

In [4]:
from torch import Tensor
from torch.utils.data import Dataset, DataLoader

In [8]:
from typing import Tuple


class JieDataSet(Dataset[Tuple[Tensor, ...]]):
    def __init__(self, *args):
        assert all(args[0].size(0) == arg.size(0) for arg in args)
        self.data = args

    def __getitem__(self, index):
        return tuple(arg[index] for arg in self.data)

    def __len__(self):
        return self.data[0].size(0)

x = torch.randn(6, 3)
y = torch.randn(6)
print(x)
print(y)
data_iter = DataLoader(JieDataSet(x, y), batch_size=2,shuffle=True)

tensor([[-0.7910,  1.1601,  1.3599],
        [-1.1130,  0.0700,  0.9740],
        [-0.1483, -1.2737,  0.2238],
        [-0.3320,  0.4956, -0.9757],
        [-0.7026, -0.9351,  0.0079],
        [-0.2209, -0.2739,  0.4359]])
tensor([-0.2379, -0.2330,  0.6021,  0.0972,  0.5812,  0.9245])


In [9]:
feature, label = next(iter(data_iter))

In [10]:
feature,label

(tensor([[-0.3320,  0.4956, -0.9757],
         [-0.7910,  1.1601,  1.3599]]),
 tensor([ 0.0972, -0.2379]))

In [3]:
a = [1, 2, 3]
b = [4, 5, 6]
print(*(a, b))

[1, 2, 3] [4, 5, 6]


In [2]:
import torch
from torch.utils import data


def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)


batch_size = 10
# data_iter = load_array((features, labels), batch_size)